//create an array using .push with prompt and also using parseInt();
var a = [];
var b = prompt("Enter 1st number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 2nd number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 3rd number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 4th number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 5th number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 6th number");
b = parseInt(b);
a.push(b);
b = prompt("Enter 7th number");
b = parseInt(b);
a.push(b);
console.log(a);